name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
jobs:

  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitLeaks Git Scan
        uses: boostsecurityio/boostsec-scanner-github@v4
        if: github.event_name == 'push'
        with:
          api_token: ${{ secrets.BOOST_API_KEY }}
          registry_module: boostsecurityio/gitleaks-full

